service: email-collector
image: iacutone/email_collector

servers:
  web:
    - "5.161.60.147"

registry:
  username: iacutone
  password:
    - DOCKER_REGISTRY_PASSWORD

proxy:
  ssl: true
  app_port: 4000
  host: email.collection.email

  healthcheck:
    interval: 5
    path: /
    timeout: 3

# Environment variables
env:
  clear:
    PHX_SERVER: true
    PORT: 4000
    SHELL: /bin/sh
  secret:
    - AWS_ACCESS_KEY
    - AWS_SECRET_KEY
    - DATABASE_PATH
    - REPLICA_URL
    - SECRET_KEY_BASE

builder:
  arch: amd64

# Persistent volumes for SQLite database
volumes:
  - "/var/lib/email_collector:/app/data"

aliases:
  console: app exec --interactive --reuse "/app/bin/email_collector remote"
  shell: app exec --interactive --reuse "/bin/sh"
  logs: app logs -f
