name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.18.4'
        otp-version: '26.2.2'

    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Build release
      run: mix release
      env:
        MIX_ENV: prod
        SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}

    - name: Create deployment package
      run: |
        tar -czf email_collector.tar.gz _build/prod/rel/email_collector/
        echo "Release package created"

    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: email-collector-release
        path: email_collector.tar.gz
        retention-days: 30

    # Add your deployment steps here
    # Examples:
    # - name: Deploy to server
    #   run: |
    #     # Your deployment commands
    #     echo "Deploying to production server"
    
    # - name: Deploy to Docker registry
    #   run: |
    #     # Build and push Docker image
    #     docker build -t your-registry/email-collector:${{ github.sha }} .
    #     docker push your-registry/email-collector:${{ github.sha }} 