name: Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.18.4'
        otp-version: '26.2.2'

    - name: Install dependencies
      run: mix deps.get

    - name: Run security audit
      run: mix deps.audit
      continue-on-error: true

    - name: Run sobelow security scan
      run: mix sobelow --config
      continue-on-error: true

    - name: Run credo code analysis
      run: mix credo --strict
      continue-on-error: true
